version: '3'

services:

  # Nginx Server
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: ngnix-server
    ports:
      - '80:80' # Connect localhost 80 port to container 80 port
    links: # Link services to access http://app and  http://api inside the container
      - api:api
      - app:app
    depends_on:
      - "api"
      - "app"

  # Frontend App
  app:
    build:
      context: ../.
      dockerfile: docker/app/Dockerfile.dev
    image: frontend-app
    env_file: 
      - ./../app/.env
    volumes: # For webpack dev server to use our local files
      - ./../app:/home/envuser/apphome
    ports:
      - '10001:10001' # For docker to now where to redirect HMR queries

  # API App
  api:
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: api-server
    env_file: 
      - ./../api/.env
    links:
      - db:db
    volumes:
      - ./../api:/home/envuser/apphome
    ports:
      - '10000:10000'
    depends_on:
      - "db"
  
  # Database
  db:
    build:
      context: ../.
      dockerfile: docker/db/postgres/Dockerfile.dev
    env_file: db/postgres/psql.env
    image: database
    env_file: ../docker/db/postgres/psql.env
    ports:
      - '5431:5432'
